version: '3.9'
services:
  frontend:
    build:
      context: ./multi-trade-vision-reactjs
    ports:
      - "602:8080"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    networks:
      - app-network

  backend:
    build:
      context: ./multi-trade-vision-api
    ports:
      - "6001:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - API_ALLOWED_ORIGINS=${API_ALLOWED_ORIGINS}
    networks:
      - app-network

  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
